In [4]:
import numpy as np

In [5]:
# !pip install numpy

## Creating Numpy 
from list

In [6]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [7]:
my_array=np.array(my_list)
my_array #array 1 dimensi

array([1, 2, 3])

In [8]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix) #array 2 dimensi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
my_3d=[[[1,2],[3,4]],
       [[5,6],[7,8]],
      [[9,10],[11,12]]]
np.array(my_3d) #3D array

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

with numpy methods

In [10]:
np.arange(0,10) #mirip range di list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2) #start di 0, stop sebelum 11, step 2 angka

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.ones(3) #membuat array berisikan angka 1

array([1., 1., 1.])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.zeros(3) #membuat array berisikan angka 0

array([0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.eye(4) #membuat matrix berisikan angka 1 di posisi diagonal dan 0 di posisi lain. Digunakan untuk perhitungan aljabar linear

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.linspace(0,10,5) #membuat angka di range tertentu dengan jarak yang sama
# start, stop, berapa angka

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.arange(0,10,5) #perhatikan bedanya dengan arange

array([0, 5])

In [24]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [25]:
np.random.rand(2) #membuat array berukuran tertentu berisikan angka acak dari 0-1

array([0.1691775 , 0.79035748])

In [26]:
np.random.rand(5,5)

array([[0.10327666, 0.35284013, 0.57611227, 0.35440575, 0.00998897],
       [0.94812757, 0.86492772, 0.13160071, 0.65695683, 0.84594582],
       [0.5245037 , 0.11005621, 0.910076  , 0.82182895, 0.61267201],
       [0.89236982, 0.94447973, 0.72629403, 0.95796751, 0.84055496],
       [0.18387364, 0.44136976, 0.44548882, 0.42459005, 0.0370214 ]])

In [27]:
np.random.randn(2) #membuat angka acak berukuran tertentu di mana distribusi angka yg dihasilkan normal

array([-1.0681223 , -0.83178045])

In [28]:
np.random.randn(5,5)

array([[-0.20729589, -1.72335449,  1.8408978 ,  0.39551769, -0.64852505],
       [-0.30800368, -0.60431525, -1.80401466, -0.78534138,  0.64404702],
       [ 1.30166425, -1.48612593,  1.42694855, -0.02898225,  2.1046902 ],
       [ 1.90176891, -1.57961487,  0.8286452 ,  2.09430152, -0.25074246],
       [-1.45964333, -0.84682021, -0.05520834, -2.31602206, -1.43198607]])

In [39]:
np.random.randint(0,10) #menghasilkan angka integer acak dari range yang kita tentukan 

6

In [40]:
np.random.randint(0,10,5) #menghasilkan angka integer acak dari 0-10, sebanyak 5 angka

array([5, 4, 2, 4, 3])

In [43]:
np.random.randint(0,10,(5,5))

array([[7, 3, 9, 4, 7],
       [3, 3, 6, 6, 1],
       [9, 7, 8, 1, 0],
       [2, 1, 7, 7, 5],
       [9, 5, 4, 2, 0]])

## Attributs and methods for numpy array

In [46]:
array_1d= np.arange(1,4)
array_2d= np.arange(1,10).reshape(3,3)
array_3d=np.arange(1,28).reshape(3,3,3)

In [47]:
array_1d

array([1, 2, 3])

In [48]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [50]:
array_1d.shape #untuk mencari ukuran array

(3,)

In [51]:
array_2d.shape #perhatikan cara penulisan, karena shape adalah attribut, maka tidak perlu ()

(3, 3)

In [52]:
array_3d.shape

(3, 3, 3)

In [54]:
my_list=[i for i in range(25)]
my_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24]

In [55]:
np.array(my_list)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
np.array(my_list).reshape(5,-1) #reshape untuk mengubah bentuk array. di contoh ini, kita ingin membuat array 2 dimensi, 
#di mana salah satu dimensi berukuran 5, dan dimensi lainnya menyesuaikan (-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
np.array(my_list).reshape(6,-1) #error karena jumlah data tidak sesuai

ValueError: cannot reshape array of size 25 into shape (6,newaxis)

In [67]:
np.array(my_list)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [63]:
np.array(my_list).reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [68]:
my_list=[i for i in range (24)]
my_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23]

In [72]:
np.array(my_list).reshape(3,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [73]:
np.array(my_list).reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [83]:
my_array= np.random.randint(1,20,10)
my_array

array([ 4,  5, 14, 11,  1,  5, 15,  8,  4,  2])

In [84]:
my_array.max() #berapa angka tertinggi di my_array

15

In [85]:
my_array.argmax() #posisi angka tertinggi

6

In [86]:
my_matrix=np.random.randint(1,20,10).reshape(2,-1)
my_matrix

array([[ 5, 11, 13,  1,  5],
       [ 6, 14, 16,  9, 10]])

In [87]:
my_matrix.max()

16

In [88]:
my_matrix.argmax() # array Ndimensi akan dianggap flat dalam penentuan posisi

7

In [89]:
my_array.min()# berapa angka terendah

1

In [91]:
my_array.argmin()#posisi angka terendah

4

In [92]:
my_array.dtype #untuk melihat tipe data isi array

dtype('int32')

In [94]:
np.linspace(0,10,5).dtype

dtype('float64')

## Indexing and Selection

In [96]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
arr[8] #menampilkan data pada posisi index 8

8

In [98]:
arr[2:7] #slicing, menampilkan data dari posisi 2 sampai sebelum posisi 7

array([2, 3, 4, 5, 6])

In [99]:
arr[0:8:2] #[start, stop, step]

array([0, 2, 4, 6])

In [100]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [101]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
arr[0]=10
arr

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
arr[2:5]=100 #slicing dapat digunakan untuk mengubah isi beberapa data sekaligus pada arry
arr

array([ 10,   1, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [104]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
slice_of_array=arr[0:5]
slice_of_array

array([0, 1, 2, 3, 4])

In [106]:
slice_of_array[:]=99
slice_of_array

array([99, 99, 99, 99, 99])

In [108]:
arr #isi arr ikut berubah sewaktu kita mengubah isi slice off array. Karena slice of array adalah view dari arr, 
#dan bukan array baru

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [109]:
arr2=arr.copy() #pakai .copy untuk menggandakan data.
arr2[1]=1000
arr2

array([  99, 1000,   99,   99,   99,    5,    6,    7,    8,    9,   10])

In [110]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

2 dimensi

In [111]:
arr_2d=np.arange(5,46,5).reshape(3,3)
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [113]:
arr_2d[1] #mengambil data di baris posisi 1

array([20, 25, 30])

In [114]:
arr_2d[1,0] #mengambil data di baris 1, kolom 0

20

In [115]:
arr_2d[1][0]

20

In [117]:
arr_2d[0,2]

15

In [118]:
arr_2d[2,1]

40

In [120]:
arr_2d[:2] #menampilkan data dimulai dari baris 0 sampai sebelum baris 2

array([[ 5, 10, 15],
       [20, 25, 30]])

In [122]:
arr_2d[:2,1:] #menampilkan data dimulai dari baris 0 sampai sebelum baris 2 
# dan kolom dimulai dari kolom 1 sampai selesai

array([[10, 15],
       [25, 30]])

In [125]:
arr_2d[:2][1:] #hasilnya berbeda, karena slicing dilakukan pada hasil slicing arr_2d[:2]

array([[20, 25, 30]])

In [126]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [127]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

Fancy Indexing

In [133]:
my_list=[0,1,2,3,4,5,6,7]
my_list[[1,2,5]] #error

TypeError: list indices must be integers or slices, not list

In [130]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [132]:
arr[[1,2,5]] #fancy indexing, memanggil data pada array secara tidak berurutan. perhatikan jumlah kurung siku yang dipakai

array([1, 2, 5])

In [134]:
[arr[1],arr[2],arr[5]] # yg dilakukan dancy indexing mirip seperti ini, tapi ini bentuknya list

[1, 2, 5]

In [135]:
arr[[9,6,3]] #bisa dengan urutan acak

array([9, 6, 3])

In [136]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [137]:
arr_2d[[0,2]] #fancy indexing pada 2d array

array([[ 5, 10, 15],
       [35, 40, 45]])

Conditional Selection

In [141]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [142]:
arr>4 #apakah nilai pada arr lebih besar dari 4. Output berupa Boolean

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [143]:
arr[arr>4] #nama_array[kondisi] #output berupa array berisikan angka yg >4 dari array arr

array([ 5,  6,  7,  8,  9, 10])

In [145]:
kondisi=arr>4
arr[kondisi]

array([ 5,  6,  7,  8,  9, 10])

In [144]:
x=2
arr[arr<x] # bisa pakai variabel di dalam kondisi

array([0, 1])

## Numpy Operation
Broadcasting

In [149]:
my_list


[0, 1, 2, 3, 4, 5, 6, 7]

In [150]:
my_list*2 #nilai di dalam list diulang 2 kali

[0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7]

In [148]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [151]:
arr*2 #nilai dalam array dikali 2 --> broadcasting

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

[0,1,2,3,4,5,6,7,8,9,10] x [2,2,2,2,2,2,2,2,2,2,2] --> yang terjadi ketika broadcasting

In [152]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [153]:
arr_2d+ np.array([1,2,3])

array([[ 6, 12, 18],
       [21, 27, 33],
       [36, 42, 48]])

In [155]:
arr_2d=np.arange(0,24).reshape(4,6)
arr_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [156]:
arr_2d+np.array([1,2,3,4])#error

ValueError: operands could not be broadcast together with shapes (4,6) (4,) 

In [157]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [158]:
1/arr 

<ipython-input-158-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [159]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [160]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [162]:
arr_2d**2

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256, 289],
       [324, 361, 400, 441, 484, 529]], dtype=int32)

In [163]:
arr_2d/arr_2d

<ipython-input-163-e50a54453c5d>:1: RuntimeWarning: invalid value encountered in true_divide
  arr_2d/arr_2d


array([[nan,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [166]:
array_2d/arr_2d #error karena ukuran tidak sesuai

ValueError: operands could not be broadcast together with shapes (3,3) (4,6) 

mathematical function

In [167]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [168]:
np.sqrt(arr) #mencari akar 

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [169]:
np.exp(arr) #mencari eksponen (e^x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [172]:
np.sin(arr) #trigonometri sin

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [173]:
 np.log(arr) # kebalikan dari exp(log natural)

<ipython-input-173-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [174]:
np.log10(100)

2.0

Other function

In [175]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [176]:
np.insert(arr,5,100) #memasukkan angka 100 di posisi index 5

array([  0,   1,   2,   3,   4, 100,   5,   6,   7,   8,   9,  10])

In [178]:
np.delete(arr,7) #menghapus angka di posisi index 7 pada array arr 

array([ 0,  1,  2,  3,  4,  5,  6,  8,  9, 10])

In [179]:
np.append(arr,100) #menambah angka 100 di posisi akhir array arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 100])

In [180]:
arr #kalau tidak disimpan, maka array arr tidak berubah

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [182]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
np.concatenate((a,b)) #secara default akan menggabungkan array pada axis 0/baris

array([[1, 2],
       [3, 4],
       [5, 6]])

In [184]:
b.T #transpose

array([[5],
       [6]])

In [186]:
np.concatenate((a,b.T),axis=1) #menggabukan pada kolom, maka axis=1
#perhatikan kalau ukuran dimensi array yg ingin digabung harus sama

array([[1, 2, 5],
       [3, 4, 6]])

In [187]:
np.concatenate((a,b),axis=None) # array yg dihasilkan 1 dimensi

array([1, 2, 3, 4, 5, 6])

In [188]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [189]:
np.where(arr>5,100,0) #np where mirip looping dengan if.
#(kondisi, yg dilakukan kalau kondisi terpenuhi, yang dilakukan kalau kondisi tidak terpenuhi)

array([  0,   0,   0,   0,   0,   0, 100, 100, 100, 100, 100])

In [190]:
np.where(arr%2==0,'genap','ganjil')

array(['genap', 'ganjil', 'genap', 'ganjil', 'genap', 'ganjil', 'genap',
       'ganjil', 'genap', 'ganjil', 'genap'], dtype='<U6')